change how hf is configured
osu-itis/ansible-splunk pull request #34
Opened 2016-09-13 21:12 UTC by akeym

I feel like I'm missing something..

2016-09-14 22:41 UTC, dubiousOne commented on roles/overrides/tasks/main.yml
> +  copy: src="{{splunk_repository.repository_root}}/conf/heavyforwarder/props.conf"
path is wrong, there is no conf/heavyforwarder directory on ansible-vd01

2016-09-14 22:47 UTC, dubiousOne commented on roles/overrides/tasks/main.yml
> +        dest="/opt/splunk/etc/system/local/props.conf"
destination file is the same in each task, should match source filename

2016-09-14 22:48 UTC, dubiousOne requested changes

2016-09-15 18:47 UTC, akeym commented
this branch has been re-worked, please review

2016-09-15 20:51 UTC, dubiousOne commented
good 2 go

2016-09-15 20:53 UTC, dubiousOne approved these changes

2016-09-15 20:53 UTC, merged